#
# Makefile for standalone compilation
#

.PHONY: modules clean install

obj-m += parport_ip32.o

modules:
	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

install:
	install -m 644 parport_ip32.ko /lib/modules/$(shell uname -r)/kernel/drivers/parport/
